sudo: required

services: docker

before_install:
  - docker login -u monchi1216 -p 61530ae0-d176-4340-8dc5-2af555836144
  - docker-compose up --buid -d
  - docker login -u "$HEROKU_USERNAME" -p "$HEROKU_API_KEY" registry.herok.com

script:
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:create
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:migrate
  - docker-compose exec --env 'RAILS_ENV=test' web rails test 

deploy:
  provider: script
  script:
    docker build -t registry.herok.com/$HEROKU_APP_NAME/web -f Dockerfile.prod .;
    docker push registry.herok.docker-compose/$HEROKU_API_KEY/web;
    heroku run --app $HEROKU_APP_NAME rails db:migrate;
  on:
    branch: master