sudo: required

services: docker

before_install:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_ACCESS_TOKEN
  DOCKERHUB_PASS: 61530ae0-d176-4340-8dc5-2af555836144
  - docker-conpose up --buid -d

script:
  - docker-compose exec --env 'RAILS_RNV=test' web rails db:create
  - docker-compose exec --env 'RAILS_RNV=test' web rails db:migrate
  - docker-compose exec --env 'RAILS_RNV=test' web rails test 