sudo: required

services: docker

before_install:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_ACCESS_TOKEN
  - docker-conpose up --buid -d

script:
  - docker-compose exec --env 'RAILS_RNV=test' web rails db:create
  - docker-compose exec --env 'RAILS_RNV=test' web rails db:migrate
  - docker-compose exec --env 'RAILS_RNV=test' web rails test 